import {MigrationInterface, QueryRunner} from "typeorm";

export class firstMigration1603541235317 implements MigrationInterface {
    name = 'firstMigration1603541235317'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `error_logger` (`errorloggerId` int NOT NULL AUTO_INCREMENT, `message` varchar(191) NULL, `appName` varchar(191) NULL, `trace` longtext NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp NULL, PRIMARY KEY (`errorloggerId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `customer` (`customerId` int NOT NULL AUTO_INCREMENT, `firstName` varchar(191) NOT NULL, `middleName` varchar(191) NOT NULL, `lastName` varchar(191) NOT NULL, `email` varchar(191) NOT NULL, `gender` enum ('male', 'female') NULL, `userName` varchar(191) NULL, `otpCode` varchar(255) NULL, `verifiedEmail` tinyint NOT NULL DEFAULT 0, `verifiedPhoneNumber` tinyint NOT NULL DEFAULT 0, `profilePhoto` text NOT NULL, `lastLng` double NULL DEFAULT 0, `lastLat` double NULL DEFAULT 0, `phone` varchar(191) NULL, `status` enum ('active', 'deactivated', 'suspended', 'testing') NULL DEFAULT 'active', `password` varchar(128) NULL, `rememberToken` varchar(191) NULL, `role` enum ('HeadOfDepartment', 'itManager', 'accountant', 'manager', 'secretary', 'staff', 'standAlone') NULL, `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`customerId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `photo` (`photoId` int NOT NULL AUTO_INCREMENT, `url` varchar(191) NOT NULL, `customerId` int NULL, `companyStaffId` int NULL, `companyId` int NULL, `photoType` enum ('ProfilePhoto', 'BannerPhoto', 'SliderPhoto', 'CoverPhoto') NULL, `isVerified` tinyint NOT NULL DEFAULT 0, `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`photoId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_staff` (`companyStaffId` int NOT NULL AUTO_INCREMENT, `firstName` varchar(191) NOT NULL, `middleName` varchar(191) NOT NULL, `lastName` varchar(191) NOT NULL, `companyId` int NULL, `email` varchar(191) NOT NULL, `gender` enum ('male', 'female') NULL, `profilePhoto` text NOT NULL, `userName` varchar(191) NULL, `verifiedEmail` tinyint NOT NULL DEFAULT 0, `verifiedPhoneNumber` tinyint NOT NULL DEFAULT 0, `phone` varchar(191) NULL, `otpCode` varchar(255) NULL, `status` enum ('active', 'deactivated', 'suspended', 'testing') NULL DEFAULT 'active', `password` varchar(128) NULL, `rememberToken` varchar(191) NULL, `role` enum ('superAdmin', 'itManager', 'accountant', 'meterReader', 'manager', 'secretary', 'staff') NULL DEFAULT 'staff', `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`companyStaffId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_staff_role` (`companyStaffRoleId` int NOT NULL AUTO_INCREMENT, `companyId` int NULL, `status` enum ('active', 'inactive') NULL, `name` varchar(255) NULL, `displayName` varchar(255) NULL, `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`companyStaffRoleId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `sms_result` (`smsResultId` int NOT NULL AUTO_INCREMENT, `companyId` int NULL, `cost` varchar(191) NULL, `messageId` varchar(191) NULL, `number` varchar(191) NULL, `status` varchar(191) NULL, `statusCode` int NULL, `messageParts` int NULL, `smsType` enum ('PasswordChange', 'UserCreated', 'Notification', 'MeterReading', 'MeterReadingEdit', 'Complaint', 'WaterBill', 'WaterBillPayment', 'CustomerCharge', 'WaterChargePayment') NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp NULL, PRIMARY KEY (`smsResultId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company` (`companyId` int NOT NULL AUTO_INCREMENT, `status` enum ('active', 'deactivated', 'suspended', 'testing') NULL DEFAULT 'testing', `isAllowManualPayments` enum ('yes', 'no') NULL DEFAULT 'no', `name` varchar(255) NULL, `country` varchar(255) NULL, `route` varchar(255) NULL, `locality` varchar(255) NULL, `smsApiKey` varchar(255) NULL, `smsUserName` varchar(255) NULL, `senderId` varchar(255) NULL, `administrative_area_level_1` varchar(255) NULL, `email` varchar(255) NULL, `businessPermitNumber` varchar(255) NULL, `businessPermitUrl` varchar(255) NULL, `emailNotifications` varchar(255) NULL, `headOffice` varchar(255) NULL, `phoneNo` varchar(255) NULL, `phoneNoNotifications` varchar(255) NULL, `startDate` datetime NULL, `endDate` datetime NULL, `logo` varchar(255) NULL, `payBillNumber` varchar(255) NULL, `registrationFee` decimal(15,2) NULL, `smsAmount` decimal(15,2) NULL, `position` point NULL, `latitude` float(10,6) NULL, `longitude` float(10,6) NULL, `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`companyId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_department` (`companyDepartmentId` int NOT NULL AUTO_INCREMENT, `companyId` int NULL, `name` varchar(191) NULL, `description` varchar(191) NULL, `status` enum ('active', 'deactivated', 'suspended', 'testing') NULL DEFAULT 'active', `email` varchar(191) NULL, `emailNotifications` varchar(191) NULL, `phoneNo` varchar(255) NULL, `phoneNoNotifications` varchar(255) NULL, `createdAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, PRIMARY KEY (`companyDepartmentId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `sms_validation_result` (`smsValidationResultId` int NOT NULL AUTO_INCREMENT, `cost` varchar(191) NULL, `messageId` varchar(191) NULL, `number` varchar(191) NULL, `status` varchar(191) NULL, `statusCode` int NULL, `smsType` enum ('PasswordChange', 'UserCreated', 'Notification', 'MeterReading', 'MeterReadingEdit', 'Complaint', 'WaterBill', 'WaterBillPayment', 'CustomerCharge', 'WaterChargePayment') NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deletedAt` timestamp NULL, PRIMARY KEY (`smsValidationResultId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_staff_role_company_staffs_company_staff` (`companyStaffRoleCompanyStaffRoleId` int NOT NULL, `companyStaffCompanyStaffId` int NOT NULL, INDEX `IDX_ce5ef9ffc1605c7184bbd6eec3` (`companyStaffRoleCompanyStaffRoleId`), INDEX `IDX_4abf79349938262d9d97e34cdb` (`companyStaffCompanyStaffId`), PRIMARY KEY (`companyStaffRoleCompanyStaffRoleId`, `companyStaffCompanyStaffId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `photo` ADD CONSTRAINT `FK_9bb49cefd25c25f62bafe5e2242` FOREIGN KEY (`customerId`) REFERENCES `photo`(`photoId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `photo` ADD CONSTRAINT `FK_8d8d1d60c556e17e41c8414cf2c` FOREIGN KEY (`companyId`) REFERENCES `photo`(`photoId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `photo` ADD CONSTRAINT `FK_538cf9bbc7a437bfb10c357bc4e` FOREIGN KEY (`companyStaffId`) REFERENCES `photo`(`photoId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_staff` ADD CONSTRAINT `FK_df851724cabf7ed56b7d2698fcb` FOREIGN KEY (`companyId`) REFERENCES `company`(`companyId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_staff_role` ADD CONSTRAINT `FK_18d40e676d02f5b4d3094eb600f` FOREIGN KEY (`companyId`) REFERENCES `company`(`companyId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `sms_result` ADD CONSTRAINT `FK_33ca599e0516c19e22b4c8e0d09` FOREIGN KEY (`companyId`) REFERENCES `company`(`companyId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_department` ADD CONSTRAINT `FK_e3d48a00607bf8480bbac590ee1` FOREIGN KEY (`companyId`) REFERENCES `company`(`companyId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_staff_role_company_staffs_company_staff` ADD CONSTRAINT `FK_ce5ef9ffc1605c7184bbd6eec38` FOREIGN KEY (`companyStaffRoleCompanyStaffRoleId`) REFERENCES `company_staff_role`(`companyStaffRoleId`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_staff_role_company_staffs_company_staff` ADD CONSTRAINT `FK_4abf79349938262d9d97e34cdbb` FOREIGN KEY (`companyStaffCompanyStaffId`) REFERENCES `company_staff`(`companyStaffId`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `company_staff_role_company_staffs_company_staff` DROP FOREIGN KEY `FK_4abf79349938262d9d97e34cdbb`");
        await queryRunner.query("ALTER TABLE `company_staff_role_company_staffs_company_staff` DROP FOREIGN KEY `FK_ce5ef9ffc1605c7184bbd6eec38`");
        await queryRunner.query("ALTER TABLE `company_department` DROP FOREIGN KEY `FK_e3d48a00607bf8480bbac590ee1`");
        await queryRunner.query("ALTER TABLE `sms_result` DROP FOREIGN KEY `FK_33ca599e0516c19e22b4c8e0d09`");
        await queryRunner.query("ALTER TABLE `company_staff_role` DROP FOREIGN KEY `FK_18d40e676d02f5b4d3094eb600f`");
        await queryRunner.query("ALTER TABLE `company_staff` DROP FOREIGN KEY `FK_df851724cabf7ed56b7d2698fcb`");
        await queryRunner.query("ALTER TABLE `photo` DROP FOREIGN KEY `FK_538cf9bbc7a437bfb10c357bc4e`");
        await queryRunner.query("ALTER TABLE `photo` DROP FOREIGN KEY `FK_8d8d1d60c556e17e41c8414cf2c`");
        await queryRunner.query("ALTER TABLE `photo` DROP FOREIGN KEY `FK_9bb49cefd25c25f62bafe5e2242`");
        await queryRunner.query("DROP INDEX `IDX_4abf79349938262d9d97e34cdb` ON `company_staff_role_company_staffs_company_staff`");
        await queryRunner.query("DROP INDEX `IDX_ce5ef9ffc1605c7184bbd6eec3` ON `company_staff_role_company_staffs_company_staff`");
        await queryRunner.query("DROP TABLE `company_staff_role_company_staffs_company_staff`");
        await queryRunner.query("DROP TABLE `sms_validation_result`");
        await queryRunner.query("DROP TABLE `company_department`");
        await queryRunner.query("DROP TABLE `company`");
        await queryRunner.query("DROP TABLE `sms_result`");
        await queryRunner.query("DROP TABLE `company_staff_role`");
        await queryRunner.query("DROP TABLE `company_staff`");
        await queryRunner.query("DROP TABLE `photo`");
        await queryRunner.query("DROP TABLE `customer`");
        await queryRunner.query("DROP TABLE `error_logger`");
    }

}
